version: '3'

services:
  app:
    build: .
    container_name: nodejs
    entrypoint: dockerize -wait tcp://db:3306 -timeout 20s docker-entrypoint.sh  
    command: "node index.js"
    networks:
      - desafio-network
    depends_on:
      - db

  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=admin 
    volumes:
      - "./db/setup.sql:/docker-entrypoint-initdb.d/setup.sql"
    networks:
      - desafio-network

  nginx:
    build: 
      context: ./nginx
    container_name: nginx
    entrypoint: dockerize -wait tcp://app:3000 -timeout 20s ./docker-entrypoint.sh
    command: ["nginx","-g","daemon off;"]
    networks:
      - desafio-network
    ports:
      - 8080:80
    depends_on:
      - app


  
networks:
    desafio-network:
      driver: bridge
    
    
    


